### ISSUE TITLE
Errores

### ISSUE THREAD

**Issue by cruzIago** [Sr-fer/Ejercicios-S22#1]
Te voy a listar los errores que tenías:

main.js
- Primero, en la linea 91, estabas llamando simplemente a "name". Eso es un objeto, tienes que enviar "name.value" para el valor, por ejemplo.
- Además, para evitar borrar todo lo que escriba el usuario cuando introduzca un número, sería buena idea que el slice en vez de (0,0) fuese (0, name.value.length-1) por ejemplo. Para que eliminase el último caracter introducido.

main.php
- Aquí el problema es más sutil. Se te pasó poner "==" en las comparaciones, por lo que fallaba directamente y no establecía ningún objeto nuevo. Además, añade mejor una variable $StRet=0; para que no cante el sistema de errores pidiendotela luego.
- Mejor usar $student1->name antes que $_POST["name"], solo como detalle.

Con los cambios que te comenté, me funciona perfectamente.

**Comment by Sr-fer** [comment]
Ya he realizado los cambios y me da error, ahora me dice que data no está declarado, he subido los cambios para ver si puedes ver por que surge esto

**Comment by cruzIago** [comment]
main.js
En la linea 95, data no existe.

main.php
Las variables no se declaran con var
